/**
 * SEO Bot Cache Index
 * Generated by scripts/update-bot-cache.js
 */
import { html as homeHtml } from './home.js';
import { html as aboutHtml } from './about.js';
import { html as privacyHtml } from './privacy.js';
import { html as contactHtml } from './contact.js';

export const BOT_CACHE: Record<string, string> = {
  "/": homeHtml,
  "/about": aboutHtml,
  "/privacy": privacyHtml,
  "/contact": contactHtml,
};
